server:
  port: ${PORT:8083}

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: producto-service
              uri: lb://producto-service
              predicates:
                - Path=/api/productos/**

            - id: usuario-service
              uri: lb://usuario-service
              predicates:
                - Path=/api/usuarios/**

eureka:
  client:
    enabled: ${EUREKA_ENABLED:false}
    register-with-eureka: ${EUREKA_ENABLED:false}
    fetch-registry: ${EUREKA_ENABLED:false}
    service-url:
      defaultZone: http://${EUREKA_HOSTPORT:localhost:8761}/eureka

  instance:
    prefer-ip-address: true