server:
  port: ${PORT:8083}

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: producto-service
              uri: lb://producto-service
              predicates:
                - Path=/api/productos/**

            - id: usuario-service
              uri: lb://usuario-service
              predicates:
                - Path=/api/usuarios/**

eureka:
  client:
    enabled: ${EUREKA_ENABLED:false}
    register-with-eureka: ${EUREKA_ENABLED:false}
    fetch-registry: ${EUREKA_ENABLED:false}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

  instance:
    hostname: ${RENDER_EXTERNAL_HOSTNAME:localhost}
    prefer-ip-address: false
    secure-port-enabled: true
    non-secure-port-enabled: false
    secure-port: 443
    home-page-url: https://${RENDER_EXTERNAL_HOSTNAME:localhost}/
    status-page-url: https://${RENDER_EXTERNAL_HOSTNAME:localhost}/
    health-check-url: https://${RENDER_EXTERNAL_HOSTNAME:localhost}/